Inital Commit

diff --git a/azure.yaml b/azure.yaml
--- a/azure.yaml
+++ b/azure.yaml
@@ -14,7 +14,14 @@ hooks:
       interactive: false
       run: |
         if [ "$GITHUB_ACTIONS" = "true" ]; then
-          bash infra/hooks/postprovision.sh 2>&1
+          if infra/hooks/postprovision.sh 2>&1; then
+            echo "Post-provision script executed successfully."
+          else
+            echo "Post-provision script failed."
+            exit 1
+          fi
+        else
+          echo "This script is intended to be run in a GitHub Actions environment."
         fi
 
 services:
