Myfeature (#4)
* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* Sandbox experiments

* evaluations

* evaluations

* my feature

* my feature

* my feature

* my feature

* my feature

* my feature

diff --git a/.github/actions/config-env/action.yml b/.github/actions/config-env/action.yml
--- a/.github/actions/config-env/action.yml
+++ b/.github/actions/config-env/action.yml
@@ -17,10 +17,14 @@ inputs:
     required: true
   MANUAL_PROVISIONING:
     description: 'Will not provision the environment if value is true, default is false'
-    required: false
+    required: true
+  AZURE_DEPLOY_APP_SERVICE:
+    description: 'Will not provision app plan and services if value is false, default is true'
+    required: true
 runs:
   using: "composite"
   steps:
+    - uses: actions/checkout@v4  
     - name: Check GitHub env variables
       shell: bash
       run: |
@@ -90,16 +94,24 @@ runs:
           exit_code=$?
           set -e
           if [ $exit_code -ne 0 ]; then
-            echo "🔶 | No previous deployment exists."
+            echo "🔶 | No previous deployment exists or failed."
             deployment_exists=false
           else
-            echo "🔶 | Previous deployment exists."
+            echo "🔶 | Previous deployment exists." 
             deployment_exists=true
           fi
+          
+          # Define azd deployAppService parameter
+          export AZURE_DEPLOY_APP_SERVICE=${{ inputs.AZURE_DEPLOY_APP_SERVICE }}
+          [ -n "$AZURE_DEPLOY_APP_SERVICE" ] && echo 'AZURE_DEPLOY_APP_SERVICE is ${AZURE_DEPLOY_APP_SERVICE}' || echo 'AZURE_DEPLOY_APP_SERVICE is empty defaulting to true'
+          [ -n "$AZURE_DEPLOY_APP_SERVICE" ] && azd env set AZURE_DEPLOY_APP_SERVICE ${AZURE_DEPLOY_APP_SERVICE} || azd env set AZURE_DEPLOY_APP_SERVICE true
+          
+          # Define azd principalType parameter
+          azd env set AZURE_PRINCIPAL_TYPE 'ServicePrincipal'
 
           # Checking if previous deployment exists
           if [  "$deployment_exists" = false ]; then
-            echo "Provisioning environment..."
+            echo "Provisioning environment..." 
             azd provision --no-prompt
           fi
 
@@ -110,10 +122,12 @@ runs:
           else
             resource_group_exist=$(az group exists --name "$AZURE_RESOURCE_GROUP")  
           fi        
-          echo "🔶 | Resource group exist status: $resource_group_exist"
+          echo "🔶 | Resource group ${AZURE_RESOURCE_GROUP:-'-'} exist status: $resource_group_exist"
 
-          # Previous deployment exists but the resource group doesn't, need to clean resources.
+          # Previous deployment exists but the resource group doesn't. 
           # This situation occurs if you made a deployment and then deleted the resource group.
+          # Resource group may also be empty because previous deployment finished with failure.
+          # In both cases we recreate resources
           if [ "$deployment_exists" = true ] && [ "$resource_group_exist" = false ]; then
             echo "🔶 | Deployment exists but resource group $AZURE_RESOURCE_GROUP doesn't, cleaning resources."
             azd down --force --purge
@@ -128,9 +142,9 @@ runs:
           # - If the new value differs from the latest deployment, the AZD variable is updated.
           # - Finally, it adds the variable to the GitHub output for use by the calling job.
 
-          echo "${{ inputs.AZURE_ENV_NAME }} environment variables values."
+          echo "${{ inputs.AZURE_ENV_NAME }} environment variables values." 
           
-          # Set environment variables
+          # Set environment variables and update AZD variables 
           
           for VAR in "${VARIABLES[@]}"; do
             VALUE_OUTPUT=$(azd env get-values -e ${{ inputs.AZURE_ENV_NAME }} | grep $VAR | cut -d'=' -f2 | tr -d '"' || true)
@@ -142,6 +156,14 @@ runs:
             export $VAR=$VALUE            
           done
 
+          # Define azd deployAppService parameter
+          export AZURE_DEPLOY_APP_SERVICE=${{ inputs.AZURE_DEPLOY_APP_SERVICE }}
+          [ -n "$AZURE_DEPLOY_APP_SERVICE" ] && echo 'AZURE_DEPLOY_APP_SERVICE is ${AZURE_DEPLOY_APP_SERVICE}' || echo 'AZURE_DEPLOY_APP_SERVICE is empty defaulting to true'
+          [ -n "$AZURE_DEPLOY_APP_SERVICE" ] && azd env set AZURE_DEPLOY_APP_SERVICE ${AZURE_DEPLOY_APP_SERVICE} || azd env set AZURE_DEPLOY_APP_SERVICE true
+          
+          # Define azd principalType parameter
+          azd env set AZURE_PRINCIPAL_TYPE 'ServicePrincipal'
+
           # Previous deployment exists. Update provisioned resources in case template has changed.
           if [  "$deployment_exists" = true ]; then
             echo "🔶 | Previous deployment exists. Updating provisioned resources..."
@@ -149,7 +171,20 @@ runs:
           fi
         fi
 
+        # Updating azd environment variables after provisioning
+
+        for VAR in "${VARIABLES[@]}"; do
+          VALUE_OUTPUT=$(azd env get-values -e ${{ inputs.AZURE_ENV_NAME }} | grep $VAR | cut -d'=' -f2 | tr -d '"' || true)
+          VALUE_GHAENV=$(eval echo \${$VAR})
+          [ -n "$VALUE_GHAENV" ] && VALUE=$VALUE_GHAENV || VALUE=$VALUE_OUTPUT
+          [ -n "$VALUE" ] && [ "$VALUE" != "$VALUE_OUTPUT" ] && azd env set $VAR $VALUE
+          echo "$VAR=$VALUE" >> "$GITHUB_OUTPUT"
+          echo "$VAR=$VALUE"
+          export $VAR=$VALUE            
+        done 
+
         # Load sample data if needed
+
         indexSampleData=$([ -z "$AZURE_SEARCH_INDEX_SAMPLE_DATA" ] || [ "$AZURE_SEARCH_INDEX_SAMPLE_DATA" == "true" ] && echo true || echo false)
         if [ $indexSampleData = "true" ]; then
           echo "🔶 | Running post-provisioning script to populate sample data." 
