Sandbox experiments

diff --git a/.github/actions/config-env/action.yml b/.github/actions/config-env/action.yml
--- a/.github/actions/config-env/action.yml
+++ b/.github/actions/config-env/action.yml
@@ -94,7 +94,7 @@ runs:
           exit_code=$?
           set -e
           if [ $exit_code -ne 0 ]; then
-            echo "🔶 | No previous deployment exists."
+            echo "🔶 | No previous deployment exists or failed."
             deployment_exists=false
           else
             echo "🔶 | Previous deployment exists." 
@@ -121,8 +121,10 @@ runs:
           fi        
           echo "🔶 | Resource group ${AZURE_RESOURCE_GROUP:-'-'} exist status: $resource_group_exist"
 
-          # Previous deployment exists but the resource group doesn't, need to clean resources. 
+          # Previous deployment exists but the resource group doesn't. 
           # This situation occurs if you made a deployment and then deleted the resource group.
+          # Resource group may also be empty because previous deployment finished with failure.
+          # In both cases we recreate resources
           if [ "$deployment_exists" = true ] && [ "$resource_group_exist" = false ]; then
             echo "🔶 | Deployment exists but resource group $AZURE_RESOURCE_GROUP doesn't, cleaning resources."
             azd down --force --purge
@@ -139,7 +141,7 @@ runs:
 
           echo "${{ inputs.AZURE_ENV_NAME }} environment variables values."
           
-          # Set environment variables
+          # Set environment variables and update AZD variables 
           
           for VAR in "${VARIABLES[@]}"; do
             VALUE_OUTPUT=$(azd env get-values -e ${{ inputs.AZURE_ENV_NAME }} | grep $VAR | cut -d'=' -f2 | tr -d '"' || true)
@@ -157,6 +159,18 @@ runs:
             azd provision --no-prompt
           fi
         fi
+
+        # Updating azd environment variables
+
+        for VAR in "${VARIABLES[@]}"; do
+          VALUE_OUTPUT=$(azd env get-values -e ${{ inputs.AZURE_ENV_NAME }} | grep $VAR | cut -d'=' -f2 | tr -d '"' || true)
+          VALUE_GHAENV=$(eval echo \${$VAR})
+          [ -n "$VALUE_GHAENV" ] && VALUE=$VALUE_GHAENV || VALUE=$VALUE_OUTPUT
+          [ -n "$VALUE" ] && [ "$VALUE" != "$VALUE_OUTPUT" ] && azd env set $VAR $VALUE
+          echo "$VAR=$VALUE" >> "$GITHUB_OUTPUT"
+          echo "$VAR=$VALUE"
+          export $VAR=$VALUE            
+        done 
 
         # Load sample data if needed
         indexSampleData=$([ -z "$AZURE_SEARCH_INDEX_SAMPLE_DATA" ] || [ "$AZURE_SEARCH_INDEX_SAMPLE_DATA" == "true" ] && echo true || echo false)
